sonar.organization=habsathedog
sonar.projectKey=HabsaTheDog_Trainscanner
sonar.projectName=Trainscanner

sonar.sources=services/orchestrator/src,frontend/src,scripts,services
sonar.tests=services/orchestrator/test
sonar.test.inclusions=services/orchestrator/test/**/*.test.js

sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.playwright-cli/**,**/reports/**,**/coverage/**
