[import]
paths=schedule:/input/gtfs

[server]
host=0.0.0.0
port=8080

[routing]
# Enable intermodal routing
extend_interval_earlier=60
extend_interval_later=60

[intermodal]
# Pedestrian routing around stations
router=ppr
ppr_profile=default
